export enum StatusEnum {
  'PAID',
  'UNPAID',
  'NOTAPPLICABLE',
  'NOTYETPAYABLE',
}

export enum OptionEnum {
  INSSURANCE = 'INSSURANCE',
  MEMBERSHIPFEE1 = 'MEMBERSH1PFEE1',
  MEMBERSHIPFEE2 = 'MEMBERSHIPFEE2',
}
